[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/property-image/*"
  to = "/.netlify/functions/image-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/vapi-llm/*"
  to = "/.netlify/functions/vapi-llm"
  status = 200
  force = true

[[redirects]]
  from = "/api/agent/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/v1/client/*/rag/*"
  to = "/.netlify/functions/rag-api"
  status = 200

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
